### ISSUE TITLE
The scope of use of each methods

### ISSUE THREAD

**Issue by hona-p** [Younes-Charfaoui/Feature-Selection-Techniques#1]
I have a question about the scope of use of the feature selection methods.
When using machine learning methods such as SVR, I have found the literature where the wrapper method has been introduced. 
On the other hand, when using deep learning methods such as LSTM, I did not find any literature that introduced the wrapper method. 
Should I use the filter method instead of the wrapper method or the embedding method because of the random bias in deep learning?

**Comment by Younes-Charfaoui** [comment]
Hey there, when using deep learning, I use the filter methods to delete a small number of nonsignificant features. That way, the neural network will have the ability to choose what best will have more impact on the final result on his own (by choosing which weights to each feature in the input methods), and this is the beauty of deep learning.

**Comment by hona-p** [comment]
Thank you for contacting me. Your very clear explanations helped me to understand!
